.PATH: ${.CURDIR}/..

PROG=dddctl

SRCS=dddctl.c parse.y base64.c dnssec.c util.c ent.c db.c raxfr.c tsig.c region.c imsg-buffer.c imsg.c sign.c query.c crypto.c

CFLAGS= -g 
CFLAGS+= -I${.CURDIR}/..  -I/usr/pkg/libressl/include -DUSE_OPENSSL
LDFLAGS= -g -L/usr/pkg/lib -L/usr/pkg/libressl/lib  -R/usr/pkg/lib -DUSE_OPENSSL
LDADD= -lcrypto -lssl -ltls

# take out -Werror
NOGCCERROR=
NOCLANGERROR=

OBJDIR=.
BINDIR=/usr/local/bin
MANDIR=/usr/local/man/man

MAN= dddctl.8

.include <bsd.prog.mk>
