.PATH: ${.CURDIR}/..

PROG=dddctl

SRCS=dddctl.c parse.y base64.c dnssec.c util.c ent.c db.c

CFLAGS= -Wall -g  -I${.CURDIR}/..
LDFLAGS= -Wall -g 
LDADD= -lcrypto -lssl

OBJDIR=.
BINDIR=/usr/local/bin
MANDIR=/usr/local/man/man

NOMAN=1

.include <bsd.prog.mk>
