.PATH: ${.CURDIR}/..

PROG=dddctl

SRCS=dddctl.c parse.y base64.c dnssec.c util.c ent.c db.c raxfr.c tsig.c region.c imsg-buffer.c imsg.c sign.c query.c crypto.c

CFLAGS= -Wall -g  -I${.CURDIR}/.. -I/usr/local/include -L/usr/local/lib -DUSE_OPENSSL
LDFLAGS= -Wall -g -L /usr/local/lib -DUSE_OPENSSL
LDADD= -lcrypto -lssl 

OBJDIR=.
BINDIR=/usr/local/bin
MANDIR=/usr/local/man/man

MAN= dddctl.8

.include <bsd.prog.mk>
