.PATH: ${.CURDIR}/..

PROG=dddctl

SRCS=dddctl.c parse.y base64.c dnssec.c util.c ent.c db.c raxfr.c tsig.c region.c

CFLAGS= -g 
CFLAGS+= -I${.CURDIR}/..  -I/usr/pkg/libressl/include
LDFLAGS= -g -L/usr/pkg/lib -L/usr/pkg/libressl/lib  -R/usr/pkg/lib
LDADD= -lcrypto -lssl 

OBJDIR=.
BINDIR=/usr/local/bin
MANDIR=/usr/local/man/man

MAN= dddctl.8

.include <bsd.prog.mk>
