.PATH: ${.CURDIR}/..

PROG=dddctl

SRCS=dddctl.c parse.y base64.c dnssec.c util.c ent.c db.c raxfr.c tsig.c region.c query.c sign.c crypto.c

CFLAGS= -Wall -g  -I${.CURDIR}/.. -DUSE_OPENSSL
LDFLAGS= -Wall -g 
LDADD= -lcrypto -lssl -lutil -ltls

OBJDIR=.
BINDIR=/usr/local/bin
MANDIR=/usr/local/man/man

MAN= dddctl.8

.include <bsd.prog.mk>
