.PATH: ${.CURDIR}/..

PROG=dd-convert

SRCS=dd-convert.c parse.y base64.c dnssec.c util.c ent.c db.c

CFLAGS= -g 
CFLAGS+= -I${.CURDIR}/..
LDFLAGS= -g -L/usr/pkg/lib -R/usr/pkg/lib
LDADD= -lcrypto -lssl 

OBJDIR=.
BINDIR=/usr/local/sbin
MANDIR=/usr/local/man/man

MAN= dd-convert.8

.include <bsd.prog.mk>
