.PATH:    ${.CURDIR}/..

PROG=delphinusdnsd

SRCS=delphinusdnsd.c parse.y reply.c additional.c region.c log.c axfr.c filter.c ratelimit.c passlist.c base64.c dnssec.c util.c ent.c db.c tsig.c raxfr.c forward.c cache.c

#CFLAGS= -DDEBUG  -g -Wall
CFLAGS= -Wall -g
CFLAGS+= -I${.CURDIR}/.. 
LDFLAGS= -Wall -g
LDADD= -lcrypto -lssl -lutil
LDLIBS= 

OBJDIR=.
BINDIR=/usr/local/sbin
MANDIR=/usr/local/man/man

MAN= delphinusdnsd.8
MAN+= delphinusdns.conf.5

.include <bsd.prog.mk>
