.PATH:    ${.CURDIR}/..

PROG=delphinusdnsd

SRCS=delphinusdnsd.c parse.y reply.c additional.c region.c log.c axfr.c filter.c ratelimit.c whitelist.c base64.c dnssec.c util.c ent.c db.c

CFLAGS= -g 
CFLAGS+= -I${.CURDIR}/.. 
LDFLAGS= -g -L/usr/pkg/lib -R/usr/pkg/lib
LDADD= -lcrypto -lssl 


OBJDIR=.
BINDIR=/usr/local/sbin
MANDIR=/usr/local/man/man

MAN= delphinusdnsd.8
MAN+= delphinusdns.conf.5

.include <bsd.prog.mk>
